// <auto-generated />
using System;
using CleanArchitectureCRUD.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitectureCRUD.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408090802_storedProcedureForCourse")]
    partial class storedProcedureForCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleanArchitectureCRUD.Domain.Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("CleanArchitectureCRUD.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credit")
                        .HasColumnType("int");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CourseId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("StudentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567801"),
                            CourseName = "Introduction to C#",
                            Credit = 3,
                            InstructorId = new Guid("f73fb6b0-9618-4dc9-0008-08de90cf5197")
                        },
                        new
                        {
                            CourseId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567802"),
                            CourseName = "ASP.NET Core Web API",
                            Credit = 4,
                            InstructorId = new Guid("74fbbc2f-7ace-4b00-0009-08de90cf5197")
                        },
                        new
                        {
                            CourseId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567803"),
                            CourseName = "Entity Framework Core",
                            Credit = 3,
                            InstructorId = new Guid("f73fb6b0-9618-4dc9-0008-08de90cf5197")
                        },
                        new
                        {
                            CourseId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567804"),
                            CourseName = "Clean Architecture Principles",
                            Credit = 4,
                            InstructorId = new Guid("74fbbc2f-7ace-4b00-0009-08de90cf5197")
                        },
                        new
                        {
                            CourseId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567805"),
                            CourseName = "Design Patterns in .NET",
                            Credit = 3,
                            InstructorId = new Guid("f73fb6b0-9618-4dc9-0008-08de90cf5197")
                        });
                });

            modelBuilder.Entity("CleanArchitectureCRUD.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CountryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonID");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("CleanArchitectureCRUD.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CleanArchitectureCRUD.Domain.Entities.Course", b =>
                {
                    b.HasOne("CleanArchitectureCRUD.Domain.Entities.Person", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanArchitectureCRUD.Domain.Entities.Student", null)
                        .WithMany("Courses")
                        .HasForeignKey("StudentId");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("CleanArchitectureCRUD.Domain.Entities.Student", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
